config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'manager/index'

  put 'manager/update'

  get 'manager/:id/update', to: 'manager#edit'

  get 'personal/index'

  get 'welcome/index'

  put 'personal/:id/update', to: 'personal#edit', as: 'patient'

  put "/personal/update"

  #get '/comment/:id' => 'comments#destroy'

  post 'welcome/like'
  #resources :statuses
  #root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #resources :articles
  root 'welcome#index'

  resources :articles do
  	resources :comments
  end
  devise_for :users, controllers: {
    :sessions => 'user/sessions',
    :registrations => 'user/registrations',
    :confirmations => 'user/confirmations',
    :omniauth_callbacks => "user/omniauth_callbacks"
  }

  match "*path", to: "application#catch_404", via: :all
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	#http_basic_authenticate_with name: "me", password: "me", only: :destroy
	before_action :set_comment, only: [:destroy, :update, :edit]
	load_and_authorize_resource

	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		#redirect_to welcome_index_path
		#redirect_to article_path(@article)
		respond_to do |format|
			format.html {redirect_to welcome_index_path @comment}
			format.js {}
           # format.json { render json: @comment}
       end
        #render :json => { :comment => comment}
    end
    def destroy
    	@comment.destroy
    	respond_to do |format|
    		format.html {redirect_to welcome_index_path @comment}
    		format.js {}
    	end
    end
    
    def edit
    	respond_to do |format|
    		format.html {redirect_to welcome_index_path @comment}
    		format.js {}
    	end
    end

    def update
        @article = Article.find(params[:article_id])
    	@comment.update(comment_params)
    	respond_to do |format|
    		format.html {redirect_to welcome_index_path @comment}
    		format.js {}
    	end
    end
	

    private
    def comment_params
    	params.require(:comment).permit(:user_id, :body)
    end

	# Use callbacks to share common setup or constraints between actions.
	def set_comment
		@comment = Comment.find(params[:id])
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id='<%= article.id.to_s + '-' + comment.id.to_s %>' style="display: flex;">
  <div class="w3-col l2 m3" style="padding: 8px;">
    <%= image_tag(comment.user.image.url, :alt=>comment.user.first_name, :style=>"width:90px;") %>
  </div>
  <div class="w3-col l10 m9">
    <h4><%= @comment.user.first_name + " " + @comment.user.last_name %> <span class="w3-opacity w3-medium"><%= time_ago_in_words comment.created_at %> ago</span></h4>
    <p id= "comment-<%= comment.id %>"><%= @comment.body %></p><br>
    <% if can? :manage, comment %>
    <p><%= link_to 'Delete', {controller: "comments", action: "destroy", id: @comment, article_id: @article.id}, remote: :true, method: :DELETE, data: { confirm: "Are you sure?"} %>|
      <%= link_to 'Edit',{controller: "comments", action: "edit", id: comment, article_id: article.id}, remote: :true %></p>
      <% end %>
    </div>
  </div>
  <div id="edit-comment-<%= comment.id %>"> </div>

app/views/comments/_comments.html.erb
<% article.comments.each do |comment| %>
<div id='<%= article.id.to_s + '-' + comment.id.to_s %>' style="display: flex;">
  <div class="w3-col l2 m3" style="padding: 8px;">
    <%= image_tag(comment.user.image.url, :alt=>comment.user.first_name, :style=>"width:90px;") if (comment.user.image?)%>
  </div>
  <div class="w3-col l10 m9">
    <h4><%= comment.user.first_name + " " + comment.user.last_name %> <span class="w3-opacity w3-medium"><%= time_ago_in_words comment.created_at %> ago</span></h4>
    <p id= "comment-<%= comment.id %>" ><%= comment.body %></p><br>
    <% if can? :manage , comment %>
    <p><%= link_to 'Delete', {controller: "comments", action: "destroy", id: comment, article_id: article.id}, remote: :true, method: :DELETE, data: { confirm: "Are you sure?"} %> |
      <%= link_to 'Edit',{controller: "comments", action: "edit", id: comment, article_id: article.id}, remote: :true %></p>
      <% end %>
    </div>
  </div>
  <div id="edit-comment-<%= comment.id %>"> </div>
  <% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment, url: article_comment_path, remote: :true) do |f| %>
<%= f.text_area :body, :cols =>50, :rows => 1 %>
<% if user_signed_in? %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<% end %>
<br>
<button onclick="cancelComment(<%= @comment.id%>, <%= @comment.article_id%>);" type="button" class="w3-button w3-red">Close</button>
<%= f.submit "Save" ,class: "w3-button w3-black"%>
<% end %>

app/views/comments/create.js.erb
$("#demo-<%= @article.id%>").append("<%= escape_javascript(render 'comments/comment', comment: @comment, article: @article) %>");
$("#count-comment-<%= @article.id%>").text(<%=@article.comments.size%>);
$("#btn-show-<%= @article.id%>").text("Ẩn bình luận");
document.getElementById("demo-<%= @article.id%>").style.display='block';
document.getElementById(<%= @article.id %>).style.display='none';

app/views/comments/destroy.js.erb
 $("#<%= @comment.article_id.to_s + '-' + @comment.id.to_s %>").remove();

app/views/comments/edit.js.erb
$("#edit-comment-<%= @comment.id %>").append("<%= escape_javascript(render 'comments/form', comment: @comment) %>");

app/views/comments/update.js.erb
$("#comment-<%= @comment.id %>").text("<%= @comment.body %>");
$("#edit-comment-<%= @comment.id %>").remove();
$("#<%= @article.id.to_s + '-' + @comment.id.to_s %>").after("<div id='edit-comment-<%= @comment.id %>'> </div>");