config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'manager/index'

  put 'manager/update'

  get 'manager/:id/update', to: 'manager#edit'

  get 'personal/index'

  get 'welcome/index'

  put 'personal/:id/update', to: 'personal#edit', as: 'patient'

  put "/personal/update"

  #get '/comment/:id' => 'comments#destroy'

  post 'welcome/like'
  #resources :statuses
  #root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #resources :articles
  root 'welcome#index'

  resources :articles do
  	resources :comments
  end
  devise_for :users, controllers: {
    :sessions => 'user/sessions',
    :registrations => 'user/registrations',
    :confirmations => 'user/confirmations',
    :omniauth_callbacks => "user/omniauth_callbacks"
  }

  match "*path", to: "application#catch_404", via: :all
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :like
	has_many :article_tag
	has_many :comments
	belongs_to :user
	
	mount_uploader :image, AvatarUploader

	validates :title, presence: true,
                    length: { minimum: 5 }

    validates :text, presence: true,
                    length: { minimum: 10 }

  after_commit :commit_success, :on => :create

  def commit_success
      puts "commit succses! :D:D"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!

  

	def show
		@article = Article.find(params[:id])
	end

	def index
    if (current_user.roles_mask == 1)
      @articles = Article.all.page(params[:page]).per(5)
    else
      @articles = Article.where(user_id: current_user.id).page(params[:page]).per(5)
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end



  def create
    ActiveRecord::Base.transaction do
     begin
      @article_save = Article.new(article_params)
      @article.user_id = current_user.id
      
      nametag = "rails"

      tag = Tag.where(name: nametag).take

      article_flag = false
      tag_flag = false
      articletag_flag = false

      if (!tag.blank?)
        
        article_flag = @article.save

        articleTag = ArticleTag.new(article_id: @article.id, tag_id: tag.id)
        articletag_flag = articleTag.save
        tag_flag = true
      else
        
        article_flag = @article.save
        
        tag = Tag.new(name: nametag)
        tag_flag = tag.save

        articleTag = Tag.new(article_id: @article.id, tag_id: tag.id)
        articletag_flag = articleTag.save
      end
      
      if (article_flag && tag_flag && articletag_flag)
        redirect_to articles_path
      else
        ActiveRecord::Rollback
        render "new"
      end
      rescue => error
       ActiveRecord::Rollback
       puts error.inspect
       render "new"
     end
   end
 end

   def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
     redirect_to articles_path
   else
     render 'edit'
   end
 end

 def destroy

  ActiveRecord::Base.transaction do
   begin

				# Delete comments
				Comment.where(article_id: params[:id]).destroy_all

				# Delete article
				@article = Article.find(params[:id])
				@article.destroy

				# Back to index
				redirect_to articles_path
			rescue => error
				ActiveRecord::Rollback
				puts error.inspect
			end
		end
	end

	private
	def article_params
		params.require(:article).permit(:title, :text, :image, :user_id)
	end
  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def img_for_article(article)
  	if article.image?
  		image_tag(article.image.url, height: '40', width: '40')
  	else
  		image_tag "default.jpg"
  	end                
  end
end

app/views/articles/create.js.erb
<% if @articles.errors.any? %>
  alert("ERROR(S): <%= j @articles.errors.full_messages.join('; ') %>")
<% else %>
  alert("Post created");
<% end %>

app/views/articles/edit.html.erb

      <h1>Edit article</h1>
      <%= form_for(@article) do |f| %>

      <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div style="margin-bottom: 25px" class="input-group ">
        <%= image_tag @article.image, id:"blah", class:"w3-bar", style:"width: 180px; height: 180px;"  %>
        <%= f.file_field :image, class: "w3-bar-item w3-button", onchange:"readURL(this);" %>
      </div>

      <div class="w3-half">
        <p>
          <%= f.text_field :title, class: "w3-input w3-border", placeholder: :title %>
        </p>
      </div>
      
      <p>
        <%= f.text_area :text, class: "w3-input w3-border", placeholder: :text, style:"height:100px;" %>
      </p>

      <div class="w3-bar w3-right" style="width:30%; margin:auto;">
        <%= link_to 'Back', articles_path, class: "w3-bar-item w3-button w3-gray", style: "width:50%"%>
        <%= f.submit("Save", class: "w3-bar-item w3-button w3-blue",style: "width:50%" )%>
      </div>
      <% end %>

app/views/articles/index.html.erb

  <h1>Listing articles</h1>
  <br>
  <%= link_to 'New article', new_article_path,class: "w3-button w3-blue"  %>
  <table class="w3-table-all">
    <thead>
      <tr class="w3-black">

        <th>Title</th>
        <th>Image</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= image_tag article.image.thumb if article.image?%></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @articles %>





































app/views/articles/new.html.erb

	<div class="row">
	<div class="col-md-12 col-md-offset-2">
			<h1>New Article</h1>
			<%= form_for :article, url: articles_path, html: { multipart: true } do |f| %>

			<% if @article.errors.any? %>
			<div id="error_explanation">
				<h2>
					<%= pluralize(@article.errors.count, "error") %> prohibited
					this article from being saved:
				</h2>
				<ul>
					<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>

			<div style="margin-bottom: 25px" class="input-group ">
				<img id="blah" class="w3-bar" style="width: 180px; height: 180px;" src="https://www.w3schools.com/w3images/team1.jpg" alt="your image" />
				<%= f.file_field :image, class: "w3-bar-item w3-button", onchange:"readURL(this);" %>
			</div>

			<div class="w3-half">
				<p>
					<%= f.text_field :title, class: "w3-input w3-border", placeholder: :title %>
				</p>
			</div>
			
			<p>
				<%= f.text_area :text, class: "w3-input w3-border", placeholder: :text, style:"height:100px;" %>
			</p>

			<div class="w3-bar w3-right" style="width:30%; margin:auto;">
				<%= link_to 'Back', articles_path, class: "w3-bar-item w3-button w3-gray", style: "width:50%"%>
				<%= f.submit("Save", class: "w3-bar-item w3-button w3-blue",style: "width:50%" )%>
			</div>
			<% end %>
		</div>
	</div>

app/views/articles/show.html.erb

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<p>
  <strong>Image:</strong>
  <%= @article.image %>
</p>

<h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.user.first_name + " " +comment.user.last_name %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>