config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'manager/index'

  put 'manager/update'

  get 'manager/:id/update', to: 'manager#edit'

  get 'personal/index'

  get 'welcome/index'

  put 'personal/:id/update', to: 'personal#edit', as: 'patient'

  put "/personal/update"

  #get '/comment/:id' => 'comments#destroy'

  post 'welcome/like'
  #resources :statuses
  #root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #resources :articles
  root 'welcome#index'

  resources :articles do
  	resources :comments
  end
  devise_for :users, controllers: {
    :sessions => 'user/sessions',
    :registrations => 'user/registrations',
    :confirmations => 'user/confirmations',
    :omniauth_callbacks => "user/omniauth_callbacks"
  }

  match "*path", to: "application#catch_404", via: :all
end

app/controllers/personal_controller.rb
class PersonalController < ApplicationController
  helper UsersHelper
  before_action :authenticate_user!
  def index
  end

  def edit
  	@user = current_user
  end
  
  def update
  	@user= current_user
  	@user.update(users_params)
  	redirect_to personal_index_path
  end
  
   # Never trust parameters from the scary internet, only allow the white list through.
    def users_params
      params.require(:user).permit(:id, :first_name, :last_name, :birthday, :image)
    end
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/views/personal/edit.html.erb
<div class="w3-col l8 s12">
  <%= form_for :user, url: "/personal/update", method: :put, html: {multipart: true} do |form| %>

  <div class="field">
    <%= form.label :first_name %><br />
    <%= form.text_field :first_name%>
  </div>

  <div class="field">
    <%= form.label :last_name %><br />
    <%= form.text_field :last_name%>
  </div>

  <div class="field">
    <%=form.label :birthday, class: "w3-xlarge" %><br />
    <%= form.date_field :birthday, autofocus: true, class: "w3-input w3-pale-blue" %>
  </div>
  <%= form.file_field :image %><br />
  <%= form.hidden_field :id %>
  <%= form.submit "Save", class: "w3-button w3-black"  %><br>
  <% end  %>
</div>

app/views/personal/index.html.erb
<div class="w3-col l8 s12">                                            
<h1 class="w3-text-black">Personal information</h1>
<%= img_for(current_user) %>
<p><span class="w3-text-red" style ="text-shadow:1px 1px 0 #444; font-size: 15pt;">Full Name: </span><%= current_user.first_name + " " + current_user.last_name %></p>
<p><span class="w3-text-red" style ="text-shadow:1px 1px 0 #444; font-size: 15pt;">Birthday:</span> <%= current_user.birthday%></p>
<p><span class="w3-text-red" style ="text-shadow:1px 1px 0 #444; font-size: 15pt;">Address:</span><%= current_user.address%></p>
<p><span class="w3-text-red" style ="text-shadow:1px 1px 0 #444; font-size: 15pt;">Religion:</span> <%= current_user.religion%></p>
<p><span class="w3-text-red" style ="text-shadow:1px 1px 0 #444; font-size: 15pt;">Description:</span> <%= current_user.describe%></p>
<%= link_to 'Change information', edit_user_registration_path, class: "w3-button w3-black"%>
<%= link_to 'Tét', patient_path(id: current_user.id), method: :PUT %>
<%= link_to "your label", current_user.first_name, :target => "_blank" %></div>