config/routes.rb
Rails.application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  get 'manager/index'

  put 'manager/update'

  get 'manager/:id/update', to: 'manager#edit'

  get 'personal/index'

  get 'welcome/index'

  put 'personal/:id/update', to: 'personal#edit', as: 'patient'

  put "/personal/update"

  #get '/comment/:id' => 'comments#destroy'

  post 'welcome/like'
  #resources :statuses
  #root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #resources :articles
  root 'welcome#index'

  resources :articles do
  	resources :comments
  end
  devise_for :users, controllers: {
    :sessions => 'user/sessions',
    :registrations => 'user/registrations',
    :confirmations => 'user/confirmations',
    :omniauth_callbacks => "user/omniauth_callbacks"
  }

  match "*path", to: "application#catch_404", via: :all
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new
    if user.has_role? :admin
        can :manage, :all
    elsif user.has_role? :user
        can :create, [Article, Comment]
        can [:update, :destroy], Article, :user_id => user.id
    #can :manage, Comment, :user => { :id => user.id }
    can :manage, Comment do |comment|
       comment.try(:user) == user
    end
    # can :destroy, Status # #uncomment this line, author can destroy status 
    can :like, WelcomeController
    can :read, [WelcomeController, Article, Comment]
    else
    can :read, [WelcomeController]
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments
	has_many :like
	has_many :article_tag
	has_many :comments
	belongs_to :user
	
	mount_uploader :image, AvatarUploader

	validates :title, presence: true,
                    length: { minimum: 5 }

    validates :text, presence: true,
                    length: { minimum: 10 }

  after_commit :commit_success, :on => :create

  def commit_success
      puts "commit succses! :D:D"
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
	belongs_to :article
	belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :article
	belongs_to :user
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :article_tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # validates :first_name, length: { in: 0..5, message: " is less 20 characters"}
  # validates :last_name, length: { in: 0..20, message: " is less 20 characters"}
  # 
  # 
  # validates :birthday, timeliness: { on_or_before: lambda { Date.current }, type: :date }
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable,
  :omniauthable, omniauth_providers: [:facebook, :google]

  has_many :comments
  has_many :articles
  mount_uploader :image, AvatarUploader
  has_many :like

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login


  ROLES = %i[admin user]

  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    roles.include?(role)
  end

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(user_name) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.confirmed_at = DateTime.now
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/controllers/manager_controller.rb
class ManagerController < ApplicationController
  before_action :authenticate_user!
  authorize_resource :class => ManagerController
  def index
    @users = Kaminari.paginate_array(User.find_by_sql(["SELECT * FROM USERS WHERE id <> ?", current_user.id])).page(params[:page]).per(5)
  end
  
  def update
    if "admin".eql? params[:roles]
      roles_mask = 1
    else
      roles_mask = 2
    end
    @user = User.find_by_id(params[:user][:id])
    @user.update(roles_mask: roles_mask)
    redirect_to manager_index_path
  end

  def edit
   @user = User.find_by_id(params[:id])
  end

  def user_roles_params
    params.require(:user).permit(:id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  helper FormattedTimeHelper
  authorize_resource class: WelcomeController

  def index
    @articles = Article.order('created_at DESC')
  end

  def like
    article_id = params[:article_id]

    like = Like.where(user_id: current_user.id, article_id: article_id).take
    liked = false

    if like.nil?
      like.destroy
    else
      like = Like.new(user_id: current_user.id, article_id: article_id)
      like.save
      liked = true
    end

    render json: { like: liked }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_title(title="")
    title + "| My Blog"
  end

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def img_for_article(article)
  	if article.image?
  		image_tag(article.image.url, height: '40', width: '40')
  	else
  		image_tag "default.jpg"
  	end                
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/formatted_time_helper.rb
module FormattedTimeHelper
  def format_time(time)
     time.blank? ? "" : time.strftime('%Y-%m-%d %I:%M:%S')
  end
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def img_for(user)
  	if user.image?
  		image_tag(user.image.url, height: '200', width: '250', :class => "w3-border")
  	else
  		image_tag "default.jpg"
  	end                
  end
end                  

app/helpers/welcome_helper.rb
module WelcomeHelper
	def img_for(user)
  	if user.image?
  		image_tag(user.image.url, height: '250', width: '200')
  	else
  		image_tag "default.jpg"
  	end                
  end
end

app/views/layouts/_footer.html.erb
 <!-- Footer -->
  <footer class="w3-container w3-dark-grey" style="padding:32px">
    <a href="#" class="w3-button w3-black w3-padding-large w3-margin-bottom"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
    <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
  </footer>

app/views/layouts/_header.html.erb
 <!-- Header -->
 <header class="w3-container w3-center w3-padding-48 w3-white">
  <h1 class="w3-xxxlarge"><b>JANE BLOGLIFE</b></h1>
  <h6>Welcome to the blog of <span class="w3-tag">Jane's world</span></h6>
</header>

<!-- Image header -->
<header id="home">
	<div class="w3-section" style="width:100%;height: 400px;display: inline-flex; margin: 0px;">
		<img class="mySlides" src="/assets/bia1.jpg" style="width:100%;">
		<img class="mySlides" src="/assets/bia2.jpg" style="width:100%;">
		<img class="mySlides" src="/assets/bia3.jpg" style="width:100%;">
	</div>
	<div class="w3-display-left w3-padding-large" style="margin-top: 160px">
		<h1 class="w3-text-white">Jane's</h1>
		<h1 class="w3-jumbo w3-text-white w3-hide-small"><b>FASHION BLOG</b></h1>
	</div>
</header>

app/views/layouts/_introMenu.html.erb
<!-- About/Information menu -->
      <div class="w3-col l4">
        <!-- About Card -->
        <div class="w3-white w3-margin">
        <% if user_signed_in? && current_user.image? %>
          <%= image_tag(current_user.image.url, class: "w3-grayscale-min", width: '100%')%>
          <div class="w3-container w3-black">
            <h4><%= current_user.first_name + ' ' + current_user.last_name%></h4>
            <p><%= current_user.describe %></p>
          </div>
        <% end%>
        </div>
        <hr>
        <!-- Posts -->
        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Popular Posts</h4>
          </div>
          <ul class="w3-ul w3-hoverable w3-white">

          <% @popularArticles.each do |article| %>
            <li class="w3-padding-16">
              <%= image_tag(article.user.image.url, :alt=>article.user.first_name, :style=>"width:50px",:class=>"w3-left w3-margin-right") %>

              <span class="w3-large"><%= article.title %></span>
              <br>
              <span><%= article.user.first_name + " " + article.user.last_name %></span>
            </li>
            <% end %>
          
          </ul>
        </div>
        <hr>

        <!-- Advertising -->
        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Advertise</h4>
          </div>
          <div class="w3-container w3-white">
            <div class="w3-container w3-display-container w3-light-grey w3-section" style="height:200px">
              <span class="w3-display-middle">Your AD Here</span>
            </div>
          </div>
        </div>
        <hr>

        <!-- Tags -->
        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Tags</h4>
          </div>
          <div class="w3-container w3-white">
            <p>
              <span class="w3-tag w3-black w3-margin-bottom">Fashion</span> 

              <% tags.each do |tag| %>
                <span class="w3-tag w3-light-grey w3-small w3-margin-bottom"><%= tag.name %></span>
              <% end %>
            </p>
          </div>
        </div>
        <hr>

        <!-- Inspiration -->
        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Inspiration</h4>
          </div>
          <div class="w3-row-padding w3-white">

            <% @inspirationArticles.each do |article| %>
            <div class="w3-col s6">
              <p><%= image_tag(article.image, :alt=>article.title, :style=>"width:100%;") %></p>
            </div>
            <% end %>
          </div>

        </div>
        <hr>

        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Follow Me</h4>
          </div>
          <div class="w3-container w3-xlarge w3-padding">
            <i class="fa fa-facebook-official w3-hover-opacity"></i>
            <i class="fa fa-instagram w3-hover-opacity"></i>
            <i class="fa fa-snapchat w3-hover-opacity"></i>
            <i class="fa fa-pinterest-p w3-hover-opacity"></i>
            <i class="fa fa-twitter w3-hover-opacity"></i>
            <i class="fa fa-linkedin w3-hover-opacity"></i>
          </div>
        </div>
        <hr>

        <!-- Subscribe -->
        <div class="w3-white w3-margin">
          <div class="w3-container w3-padding w3-black">
            <h4>Subscribe</h4>
          </div>
          <div class="w3-container w3-white">
            <p>Enter your e-mail below and get notified on the latest blog posts.</p>
            <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
            <p><button type="button" onclick="document.getElementById('subscribe').style.display='block'" class="w3-button w3-block w3-red">Subscribe</button></p>
          </div>
        </div>

        <!-- END About/Intro Menu -->
      </div>

app/views/layouts/_nav.html.erb
<!-- Navigation bar with social media icons -->
<div class="w3-bar w3-black w3-hide-small">
	<a href="#" class="w3-bar-item w3-button"><i class="fa fa-facebook-official"></i></a>
	<a href="#" class="w3-bar-item w3-button"><i class="fa fa-instagram"></i></a>
	<a href="#" class="w3-bar-item w3-button"><i class="fa fa-snapchat"></i></a>

	<% if user_signed_in? %>

  <%= button_to "Home", root_path, method: :get, class: "w3-bar-item w3-button" %>

		<% if current_user.roles_mask == 1 %>
			<%= link_to "Manager", manager_index_path, class: "w3-bar-item w3-button"%>
		<% end %>
		
		<div class="dropdown w3-bar-item w3-button w3-right">
			<span><%= current_user.first_name + " " + current_user.last_name %></span>
			<div class="dropdown-content w3-right">
				<%= link_to "Articles", articles_path%>
				<%= link_to "About", personal_index_path%>
				<%= link_to "Sign out", destroy_user_session_path, method: :delete%>
			</div>
		</div>
	<% else %>
			<button onclick="showModalSignin();" class="w3-bar-item w3-button w3-right">Sign in</button>

			<button onclick="showModalSignup();" class="w3-bar-item w3-button w3-right">Sign up</button>

		
		<%#= link_to "Sign in", new_user_session_path, class: "w3-bar-item w3-button w3-right"%>
		<%#= link_to "Sign up", new_user_registration_path, method: :get, class: "w3-bar-item w3-button w3-right"%>
	<% end %>

	<a href="#" class="w3-bar-item w3-button "><i class="fa fa-search"></i></a>
</div>

<!-- START MODAL SIGN IN -->
<div id="modelSignIn" class="w3-modal modal">
  <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:400px">

    <div class="w3-center"><br>
      <span onclick="hideModalSignin()" class="w3-button w3-hover-red w3-display-topright" title="Close Modal">&times;</span>
      <img src="/assets/cas-padlock-icon.png" alt="Avatar" style="width:15%" class="w3-circle w3-margin-top">
    </div>

    <!-- <form class="w3-container" action="/action_page.php"> -->
    <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: {id: "login-form", class: "w3-container", onsubmit: "signin(this, event);"}) do |f| %>
    
      <div class="w3-section">
        <p id="error-message-login-form" class = "w3-text-red"></p>
        <b><%= f.label :login %></b>
		    <%= f.text_field :login, class: "w3-input w3-border w3-margin-bottom", placeholder:"Enter Username", required: true %>

        <b><%= f.label :password %></b>

        <%= f.password_field :password, autocomplete: "off", class: "w3-input w3-border", placeholder: "Enter Password", required: true %>
        
        <!-- <input class="w3-check w3-margin-top" type="checkbox" checked="checked"> Remember me -->

        <%= f.check_box :remember_me, class: "w3-check w3-margin-top" %> Remember me
        <p class="w3-text-blue w3-right w3-margin-top">
        <a onclick="showModalSignup();" class="">Register</a></p>
        
        <button class="w3-button w3-block w3-green w3-section w3-padding" type="submit">Sign in</button>
        <% end %>
        <div class="w3-cell-row">
          <%- if devise_mapping.omniauthable? %>
            <%#- resource_class.omniauth_providers.each do |provider| %>

              <%#- if nil.try(:resource_class) %>
              <div class="w3-container w3-blue w3-cell w3-mobile" style="padding: 0">
                <%= button_to "Sign in with facebook", omniauth_authorize_path(resource_name, "facebook"), class: "w3-button w3-block w3-padding" %>
              </div>
              <%# end -%> 
              
              <p style="width: 2px;"/>
              <div class="w3-container w3-red w3-cell w3-mobile" style="padding: 0">
                <%= button_to "Sign in with google", omniauth_authorize_path(resource_name, "google"), class: "w3-button w3-block w3-padding" %>
              </div>
            <%# end -%> 
          <% end -%>
        </div>
      </div>
    
    <!-- </form> -->

    <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
      <button onclick="hideModalSignin()" type="button" class="w3-button w3-red">Cancel</button>
      <span class="w3-right w3-padding w3-hide-small">Forgot <a href="#">password?</a></span>
    </div>

  </div>
</div>
<!-- END MODAL SIGN IN -->

<!-- START MODAL SIGN UP -->
<div id="modelSignUp" class="w3-modal modal">
  <div class="w3-modal-content w3-card-4 w3-animate-zoom" style="max-width:600px">

    <div class="w3-center"><br>
      <span onclick="hideModalSignup();" class="w3-button w3-hover-red w3-display-topright" title="Close Modal">&times;</span>
      <img src="/assets/register-education.png" alt="Avatar" style="width:10%" class="w3-circle w3-margin-top">
    </div>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {id: "new-user-form",class: "w3-container",onsubmit: "signin(this, event);"}) do |f| %>
    <div class="w3-section">
      <p id="error-message-new-user-form" class = "w3-text-red"></p>
      
      <b><%= f.label :your_name %></b>
      <div class="w3-cell-row">
        <div class="w3-container w3-cell" style="width: 50%; padding: 0">
          <%= f.text_field :first_name, required: true, class: "w3-input w3-border w3-margin-bottom", placeholder:"First name" %>
        </div>
        <div class="w3-container w3-cell" style="width: 50%; padding: 0">
          <%= f.text_field :last_name, required: true, class: "w3-input w3-border w3-margin-bottom", placeholder:"Last name" %>
        </div>
      </div>

      <b><%= f.label :email %></b>
      <%= f.email_field :email, required: true, class: "w3-input w3-border w3-margin-bottom", placeholder:"Enter email" %>

      <b><%= f.label :password %></b>
      <%= f.password_field :password, required: true, class: "w3-input w3-border w3-margin-bottom", placeholder:"Enter password" %>

      <b><%= f.label :password_confirmation %></b>
      <%= f.password_field :password_confirmation, required: true , class: "w3-input w3-border w3-margin-bottom", placeholder:"Enter password again", autocomplete: "off" %>


      <button class="w3-button w3-block w3-green w3-section w3-padding" type="submit">Sign up</button>
    </div>
    <% end %>
    <!-- </form> -->

    <div class="w3-container w3-border-top w3-padding-12 w3-light-grey">
      <span class="w3-right w3-padding w3-hide-small"><a onclick="showModalSignin();">Sign in</a></span>
    </div>

  </div>
</div>
<!-- END MODAL SIGN UP -->

app/views/layouts/_subscribe.html.erb
<!-- Subscribe Modal -->
  <div id="subscribe" class="w3-modal w3-animate-opacity">
    <div class="w3-modal-content" style="padding:32px">
      <div class="w3-container w3-white">
        <i onclick="document.getElementById('subscribe').style.display='none'" class="fa fa-remove w3-transparent w3-button w3-xlarge w3-right"></i>
        <h2 class="w3-wide">SUBSCRIBE</h2>
        <p>Join my mailing list to receive updates on the latest blog posts and other things.</p>
        <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
        <button type="button" class="w3-button w3-block w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('subscribe').style.display='none'">Subscribe</button>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= make_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    h1,h2,h3,h4,h5,h6 {font-family: "Oswald"}
    body {font-family: "Open Sans"}

    .mySlides {display:none}
  </style>
</head>

<body class="w3-light-grey">
<% if flash[:alert] %>
    <div class="alert"><%= flash[:alert] %></div>
<% end %>
<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <!-- Navigation bar with social media icons -->
  <%= render  "layouts/nav" %>
  <!-- END Navigation bar with social media icons -->
<!-- w3-content defines a container for fixed size centered content,
  and is wrapped around the whole page content, except for the footer in this example -->
  <div class="w3-content" style="max-width:1600px">
    <!-- Header -->
    <%= render  "layouts/header" %>
    <!-- END Header -->

    <!-- Grid -->
    <div class="w3-row w3-padding w3-border">

      <!-- START Custom content -->
      <div class="w3-col l8 s12 container-articles">
      <%= yield %>
      </div>
      <!-- END Custom content -->

      <!-- START About/Intro Menu -->
      <%= render  "layouts/introMenu", popularArticles: @popularArticles, inspirationArticles: @inspirationArticles, tags: @tags %>
      <!-- END About/Intro Menu -->
      <!-- END GRID -->
    </div>
    <!-- END w3-content -->
  </div>
  <!-- Subscribe Modal -->
  <%= render  "layouts/subscribe" %>
  <!-- END Subscribe Modal -->
  <!-- Footer -->
  <%= render  "layouts/footer" %>
  <!-- END Footer -->
  
</body>
</html>